version: "3.9"
 
services:
  db:
    container_name: mariadb
    image: mariadb:10.8-jammy
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=orangehrm
    ports:
      - 3306:3306
    networks:
      - orangehrm
 
  orangehrm:
    container_name: orangehrm
    build: ./orangehrm
    restart: unless-stopped
    volumes:
      - orangehrm:/var/www/html:delegated
    ports:
      - 8000:80
      - 8443:443
    networks:
      - orangehrm
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
 
networks:
  orangehrm:
    driver: bridge