version: "3.9"
 
services:
  db:
    container_name: mariadb
    image: mariadb:10.8-jammy
    restart: unless-stopped
    volumes:
      - /docker/orangehrm/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=orangehrm
    ports:
      - 3306:3306
    networks:
      - orangehrm
 
  orangehrm:
    container_name: orangehrm
    build: 
      dockerfile: Dockerfile-local
    pull_policy: build
    restart: unless-stopped
    #volumes:
    #  - /docker/orangehrm/html:/var/www/html:delegated #
    # comment for redeploy
    environment:
      - ORANGEHRM_DATABASE_USER=${ORANGEHRM_DATABASE_USER}
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_NAME=${ORANGEHRM_DATABASE_NAME}
      - ORANGEHRM_DATABASE_PASSWORD=${ORANGEHRM_DATABASE_PASSWORD}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - VIRTUAL_HOST=hrm.dev.razum.si
      - VIRTUAL_PORT=80
    networks:
      - orangehrm
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
 
networks:
  orangehrm:
    driver: bridge
